routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Shipping\ByCartAmountShipping\Http\Controllers\ByCartAmountAdminController;
use Illuminate\Support\Facades\Route;

Route::prefix('bpanel/envio')->name('bpanel4-shipping.by-cart-amount.bpanel.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/metodos-de-envio/ByCartAmount/{zone}/crear', [ByCartAmountAdminController::class, 'create'])->name('create');
        Route::post('/metodos-de-envio/ByCartAmount/{zone}/crear', [ByCartAmountAdminController::class, 'store'])->name('store');
        Route::get('/metodos-de-envio/ByCartAmount/{model}/editar', [ByCartAmountAdminController::class, 'edit'])->name('edit');
        Route::post('/metodos-de-envio/ByCartAmount/{model}/editar', [ByCartAmountAdminController::class, 'update'])->name('update');
        Route::delete('/metodos-de-envio/ByCartAmount/{model}/eliminar', [ByCartAmountAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/_form.blade.php
<form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
    @csrf
    @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-by-cart-amount::form.name'),
    'required'=>true, 'value' => old('name') ?? $model?->getName() ])
    @livewire('bpanel4-by-cart-amount::steps-component', ['initialSteps' => $model?->getSteps()])
    <div class="col-12 mt-3 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
        @livewire('form::save-button',['theme'=>'update'])
        @livewire('form::save-button',['theme'=>'reset'])
    </div>
    @if (null !== $model)
        <input type="hidden" name="id" value="{{ $model->getId() }}">
        <input type="hidden" name="shipping_zone_id" value="{{ $model->getShippingZoneId() }}">
    @else
        <input type="hidden" name="shipping_zone_id" value="{{ $zone->getId() }}">
    @endif
</form>
@if($errors->any())
    {{ implode('', $errors->all('<div>:message</div>')) }}
@endif

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-by-cart-amount::form.create-by-cart-amount'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-by-cart-amount::form.create-by-cart-amount') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-shipping.by-cart-amount.bpanel.store', [
            'zone' => $zone,
            'model' => $model,
        ])}}">
            @include('bpanel4-by-cart-amount::bpanel._form', ['panelTitle' => __('bpanel4-by-cart-amount::form.create-by-cart-amount')])
        </form>
    </div>

@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-by-cart-amount::form.edit-by-cart-amount'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-by-cart-amount::form.edit-by-cart-amount') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-shipping.by-cart-amount.bpanel.update', [
            'model' => $model,
        ])}}">
            @include('bpanel4-by-cart-amount::bpanel._form', ['panelTitle' => __('bpanel4-by-cart-amount::form.edit-by-cart-amount')])
        </form>
    </div>

@endsection

resources/views/bpanel/livewire/steps-component.blade.php
<div>
    <div class="form-group form-row">
        <div class="col-sm-3 col-form-label text-sm-right">
            <label for="id-form-field-1" class="mb-0  ">
                <span class="text-danger">*</span>  Tramos de precio
            </label>
        </div>
        <div class="col-sm-7">
            <div class="input-group by-cart-amount-steps mb-2">
                @foreach($steps as $key => $step)
                    <div class="form-row row mb-2 w-100">
                        <div class="input-group col-5">
                            <label class="w-100 col-form-label">Importe mínimo</label>
                            <input type="number" name="steps[{{ $key }}][minimum]" step="0.01" min="0" wire:model="steps.{{$key}}.minimum" class="form-control">
                        </div>
                        <div class="input-group col-5">
                            <label class="w-100 col-form-label">Precio</label>
                            <input type="number" name="steps[{{ $key }}][price]" step="0.01" min="0" wire:model="steps.{{$key}}.price" class="form-control">
                        </div>
                        <div class="col-2 d-flex justify-content-center align-items-end">
                            <button wire:click.prevent="removeRow({{$key}})" class="remove">X</button>
                        </div>
                    </div>
                @endforeach
            </div>
            <button class="btn btn-primary" wire:click.prevent="addStep"><i class="fas fa-plus"></i> Añadir escalón</button>
        </div>
    </div>
    @push('styles')
        <link rel="stylesheet" href="{{ Vite::asset('vendor/bittacora/bpanel4-shipping-by-cart-amount/resources/assets/scss/by-cart-amount-shipping.scss') }}"/>
    @endpush
</div>